//! Docker container management for the host tier of the `#[in_vm]` test
//! infrastructure.
//!
//! This module launches a privileged Docker container with the devices and
//! capabilities required to boot a cloud-hypervisor VM, then re-executes the
//! test binary inside it.

use bollard::query_parameters::{
    CreateContainerOptions, InspectContainerOptions, RemoveContainerOptions, StartContainerOptions,
};
use bollard::secret::{
    ContainerCreateBody, DeviceMapping, HostConfig, MountBindOptions,
    RestartPolicy, RestartPolicyNameEnum,
};
use n_vm_protocol::{
    CONTAINER_IMAGE, CONTAINER_PLATFORM, ENV_IN_TEST_CONTAINER, ENV_MARKER_VALUE,
    VM_ROOT_SHARE_PATH,
};
use tokio_stream::StreamExt;

/// The result of running a test inside a Docker container.
///
/// This is a lightweight wrapper that avoids exposing the `bollard` crate's
/// [`ContainerState`](bollard::secret::ContainerState) type as part of the
/// public API.
#[derive(Debug)]
pub struct ContainerTestResult {
    /// The exit code of the container's main process, if available.
    pub exit_code: Option<i64>,
}

/// Launches a Docker container and re-runs the current test binary inside it.
///
/// This is the **host-tier** entry point, called from the code generated by
/// `#[in_vm]` when neither `IN_VM` nor `IN_TEST_CONTAINER` is set (i.e. a
/// normal `cargo test` invocation).  It:
///
/// 1. Connects to the local Docker daemon.
/// 2. Creates a container from the `n-vm` test image with the required devices
///    (`/dev/kvm`, `/dev/vhost-vsock`, `/dev/vhost-net`, `/dev/net/tun`) and
///    Linux capabilities (`SYS_CHROOT`, `NET_ADMIN`, etc.).
/// 3. Bind-mounts the test binary directory into the container.
/// 4. Starts the container with `IN_TEST_CONTAINER=YES` and streams its
///    stdout/stderr to the host's stdout/stderr.
/// 5. Waits for the container to exit and returns a [`ContainerTestResult`].
///
/// The type parameter `F` is used only to derive the test name via
/// [`std::any::type_name`]; the function itself is never called in this tier.
pub fn run_test_in_vm<F: FnOnce()>(_test_fn: F) -> ContainerTestResult {
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("failed to build tokio runtime for test container");
    runtime.block_on(async {
        const REQUIRED_CAPS: [&str; 6] = [
            "SYS_CHROOT", // for chroot (required by virtiofsd)
            "SYS_RAWIO", // for af-packet
            "IPC_LOCK", // for hugepages
            "NET_ADMIN", // to test creation / configuration of network interfaces and to create tap devices to hook to the vm
            "NET_RAW", // to test creation / configuration of network interfaces and to create tap devices to hook to the vm
            "NET_BIND_SERVICE", // for vsockets
        ];
        const REQUIRED_DEVICES: [&str; 4] = ["/dev/kvm", "/dev/vhost-vsock", "/dev/vhost-net", "/dev/net/tun"];
        let docker_host = std::env::var("DOCKER_HOST").unwrap_or("/var/run/docker.sock".into()).trim_start_matches("unix://").to_string();
        let required_files: [String; _] = [
            "/dev/kvm".into(), // to launch vms
            "/dev/vhost-vsock".into(), // for vsock communication with the vm
            "/dev/vhost-net".into(), // for network communication with the vm
            docker_host, // allows the launch of sibling containers (may not be needed)
        ];
        let (_, test_name) = std::any::type_name::<F>()
            .split_once("::")
            .expect("type_name did not contain '::' separator for test name");
        let bin_path = std::fs::read_link("/proc/self/exe")
            .expect("failed to read /proc/self/exe symlink");
        let bin_parent = bin_path
            .parent()
            .expect("test binary path has no parent directory");
        let bin_dir = std::fs::canonicalize(bin_parent)
            .expect("failed to canonicalize test binary directory");
        let bin_dir_str = bin_dir
            .to_str()
            .expect("test binary directory path is not valid UTF-8");
        let client = bollard::Docker::connect_with_unix_defaults()
            .expect("failed to connect to Docker daemon");
        use std::os::unix::fs::MetadataExt;
        let cap_add = REQUIRED_CAPS.map(|cap| cap.into()).into();
        let add_groups = required_files
            .map(|path| {
                std::fs::metadata(&path)
                    .unwrap_or_else(|e| panic!("failed to stat required device {path}: {e}"))
                    .gid()
                    .to_string()
            })
            .into();
        let devices = REQUIRED_DEVICES
            .map(|path| DeviceMapping {
                path_on_host: Some(path.into()),
                path_in_container: Some(path.into()),
                cgroup_permissions: Some("rwm".into()),
            })
            .into();
        let bin_path_str = bin_path
            .to_str()
            .expect("test binary path is not valid UTF-8");
        let args = [bin_path_str.to_string()]
            .into_iter()
            .chain([test_name.to_string(), "--exact".into(), "--format=terse".into()])
            .collect();
        let uid = nix::unistd::getuid().as_raw();
        let gid = nix::unistd::getgid().as_raw();
        let container = client.create_container(
            Some(CreateContainerOptions {
                name: None,
                platform: CONTAINER_PLATFORM.into(),
            }),
            ContainerCreateBody {
                entrypoint: None,
                cmd: Some(args),
                image: Some(CONTAINER_IMAGE.into()),
                network_disabled: Some(true),
                env: Some([
                    format!("{ENV_IN_TEST_CONTAINER}={ENV_MARKER_VALUE}"),
                    "RUST_BACKTRACE=1".into(),
                ].into()),
                user: Some(format!("{uid}:{gid}")),
                host_config: Some(HostConfig {
                    devices: Some(devices),
                    group_add: Some(add_groups),
                    init: Some(true),
                    network_mode: Some("none".into()),
                    restart_policy: Some(RestartPolicy {
                        name: Some(RestartPolicyNameEnum::NO),
                        ..Default::default()
                    }),
                    auto_remove: Some(false),
                    readonly_rootfs: Some(true),
                    mounts: Some([
                        bollard::models::Mount {
                            source: Some(bin_dir_str.into()),
                            target: Some(bin_dir_str.into()),
                            typ: Some(bollard::secret::MountTypeEnum::BIND),
                            read_only: Some(true),
                            bind_options: Some(MountBindOptions {
                                propagation: Some(bollard::secret::MountBindOptionsPropagationEnum::PRIVATE),
                                non_recursive: Some(true),
                                create_mountpoint: Some(true),
                                ..Default::default()
                            }),
                            ..Default::default()
                        },
                        bollard::models::Mount {
                            source: Some(bin_dir_str.into()),
                            target: Some(format!("{}/{}", VM_ROOT_SHARE_PATH, bin_dir_str)),
                            typ: Some(bollard::secret::MountTypeEnum::BIND),
                            read_only: Some(true),
                            bind_options: Some(MountBindOptions {
                                propagation: Some(bollard::secret::MountBindOptionsPropagationEnum::PRIVATE),
                                non_recursive: Some(true),
                                create_mountpoint: Some(true),
                                ..Default::default()
                            }),
                            ..Default::default()
                        }
                    ].into()),
                    tmpfs: Some({
                        let mut map = std::collections::HashMap::new();
                        map.insert("/vm".into(), format!("nodev,noexec,nosuid,uid={uid},gid={gid}"));
                        map
                    }),
                    privileged: Some(false),
                    cap_add: Some(cap_add),
                    cap_drop: Some(["ALL".into()].into()),
                    ..Default::default()
                }),
                ..Default::default()
            }
        ).await.expect("failed to create Docker container");
        client
            .start_container(&container.id, None::<StartContainerOptions>)
            .await
            .expect("failed to start Docker container");
        let mut logs = client.logs(
            &container.id,
            Some(bollard::query_parameters::LogsOptions {
                follow: true,
                stdout: true,
                stderr: true,
                tail: "all".into(),
                ..Default::default()
            }),
        );
        while let Some(log) = logs.next().await {
            match log {
                Ok(msg) => match msg {
                    bollard::container::LogOutput::StdErr { message } => {
                        eprint!(
                            "{message}",
                            message = String::from_utf8_lossy(&message)
                        );
                    }
                    bollard::container::LogOutput::StdOut { message }
                    | bollard::container::LogOutput::Console { message } => {
                        print!(
                            "{message}",
                            message = String::from_utf8_lossy(&message)
                        );
                    }
                    bollard::container::LogOutput::StdIn { .. } => unreachable!(),
                },
                Err(e) => {
                    panic!("error reading container logs: {e:#?}");
                }
            }
        }
        let state = client
            .inspect_container(&container.id, None::<InspectContainerOptions>)
            .await
            .expect("failed to inspect container after exit")
            .state
            .expect("container inspection returned no state");
        client
            .remove_container(&container.id, None::<RemoveContainerOptions>)
            .await
            .expect("failed to remove container");
        ContainerTestResult {
            exit_code: state.exit_code,
        }
    })
}