// SPDX-License-Identifier: Apache-2.0
// Copyright Open Network Fabric Authors

#![deny(unsafe_op_in_unsafe_fn)]
#![warn(missing_docs)]

//! Runtime support for the `#[in_vm]` test macro.
//!
//! This crate implements the two outer tiers of the nested test environment:
//!
//! - **Host tier** ([`run_test_in_vm`]) -- launches a Docker container with the
//!   required devices and capabilities.
//! - **Container tier** ([`run_in_vm`] / [`TestVm`]) -- launches a VM via a
//!   pluggable [`HypervisorBackend`], monitors lifecycle events, and collects
//!   test output.
//!
//! The innermost tier (the VM guest init system) is provided by the `n-it`
//! crate.
//!
//! # Hypervisor backends
//!
//! The [`backend`] module defines the [`HypervisorBackend`] trait that
//! abstracts over different hypervisors.  The [`cloud_hypervisor`] module
//! provides the default implementation ([`CloudHypervisor`]).
//!
//! [`TestVm`], [`run_in_vm`], and [`run_container_tier`] are all generic
//! over the backend.  The `#[in_vm]` proc macro currently instantiates
//! them with [`CloudHypervisor`], but callers can substitute any backend
//! that implements [`HypervisorBackend`].
//!
//! # Error handling
//!
//! Both entry points return [`Result`] with dedicated error types
//! ([`VmError`] and [`ContainerError`]) so that callers can distinguish
//! infrastructure failures from test failures.
//!
//! # Protocol constants
//!
//! This crate re-exports all constants from [`n_vm_protocol`] so that code
//! generated by the `#[in_vm]` proc macro can reference them via `::n_vm::`
//! without requiring downstream crates to add `n-vm-protocol` as a direct
//! dependency.

pub mod backend;
pub mod cloud_hypervisor;
pub mod dispatch;
pub mod error;

mod abort_on_drop;
mod container;
mod test_identity;
mod vm;

pub use backend::{HypervisorBackend, HypervisorVerdict, LaunchedHypervisor};
pub use cloud_hypervisor::CloudHypervisor;
pub use container::{ContainerTestResult, run_test_in_vm};
pub use dispatch::{is_in_test_container, is_in_vm, run_container_tier, run_host_tier};
pub use error::{ContainerError, VmError};
pub use n_vm_macros::in_vm;
pub use n_vm_protocol::{
    CLOUD_HYPERVISOR_BINARY_PATH, CONTAINER_IMAGE, CONTAINER_PLATFORM, ENV_IN_TEST_CONTAINER,
    ENV_IN_VM, ENV_MARKER_VALUE, HYPERVISOR_API_SOCKET_PATH, INIT_BINARY_PATH,
    KERNEL_CONSOLE_SOCKET_PATH, KERNEL_IMAGE_PATH, VHOST_VSOCK_SOCKET_PATH, VIRTIOFS_ROOT_TAG,
    VIRTIOFSD_BINARY_PATH, VIRTIOFSD_SOCKET_PATH, VM_GUEST_CID, VM_ROOT_SHARE_PATH, VM_RUN_DIR,
    VsockChannel, VsockCid, VsockPort,
};
pub use vm::{ProcessOutput, TestVm, TestVmParams, VmTestOutput, run_in_vm};